### ISSUE TITLE
training doesn't work

### ISSUE THREAD

**Issue by swartchris8** [obe-dl/social-media-comment-classification#1]
After cloning the repo and installing all dependencies I am having trouble training the model.

Running:
```
python lstm.py train en
```
I get:
```
Text0 sequences: 94001 Text1 sequences: 94001
Not enough sequences
```

Any advice what do I need to train the model?

**Comment by Epokhe** [comment]
Changing `sequence_count` to 9e+4 should work(english dataset is smaller)
https://github.com/obe-dl/social-media-comment-classification/blob/a5e91fc493ab5782572e580d464de3d168499d9c/scripts/lstm.py#L38
